"""sprint3_product_extension

Revision ID: 3b9dcb255647
Revises: 
Create Date: 2026-06-20 14:46:41.729218

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3b9dcb255647'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('price', sa.Numeric(precision=10, scale=2), server_default='0.00', nullable=False, comment='价格'))
    op.add_column('products', sa.Column('stock', sa.Integer(), server_default='0', nullable=False, comment='库存量'))
    op.add_column('products', sa.Column('attrs', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='其他属性'))
    op.add_column('products', sa.Column('search_vector', postgresql.TSVECTOR(), nullable=True))
    op.create_index('ix_products_search_vector', 'products', ['search_vector'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_products_search_vector', table_name='products', postgresql_using='gin')
    op.drop_column('products', 'search_vector')
    op.drop_column('products', 'attrs')
    op.drop_column('products', 'stock')
    op.drop_column('products', 'price')
    # ### end Alembic commands ###
